[tools]
yq = "latest"
jq = "latest"
k6 = "latest"
crystal = "latest"
dart = "3.4.4"
flutter = "3.22.3"
gleam = "latest"
maven = "latest"
node = "latest"
packer = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
dive = "latest"
k9s = "latest"
kubespy = "latest"
helm = "latest"
minikube = "latest"
terraform = "latest"
kubectl = "latest"

[env]
