[tools]
yq = "latest"
jq = "latest"
k6 = "latest"
crystal = "latest"
dart = "3.10.9"
flutter = "3.38.8-stable"
go = "latest"
maven = "latest"
packer = "latest"
rust = "latest"
dive = "latest"
k9s = "latest"
kubespy = "latest"
helm = "latest"
minikube = "latest"
terraform = "latest"

[env]
